apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  ai-subsidy-alerts.yml: |
    groups:
    - name: ai-subsidy.rules
      rules:
      # Application Health
      - alert: ApplicationDown
        expr: up{job="ai-subsidy-backend"} == 0
        for: 5m
        labels:
          severity: critical
          service: backend
        annotations:
          summary: "AI Subsidy application is down"
          description: "The AI Subsidy backend application has been down for more than 5 minutes"
      
      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="ai-subsidy-backend"}[5m])) > 2
        for: 10m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s"
      
      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{job="ai-subsidy-backend",status=~"5.."}[5m]) / rate(http_requests_total{job="ai-subsidy-backend"}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
          service: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }}"
      
      # Database Connection Issues
      - alert: DatabaseConnectionFailure
        expr: increase(database_connections_failed_total[5m]) > 5
        for: 2m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Database connection failures"
          description: "{{ $value }} database connection failures in the last 5 minutes"
      
      # AI Service Issues
      - alert: AIServiceHighLatency
        expr: histogram_quantile(0.95, rate(ai_request_duration_seconds_bucket[5m])) > 10
        for: 5m
        labels:
          severity: warning
          service: ai
        annotations:
          summary: "AI service high latency"
          description: "AI service 95th percentile latency is {{ $value }}s"
      
      # Resource Usage
      - alert: HighCPUUsage
        expr: (100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 85
        for: 10m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"
      
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: critical
          service: infrastructure
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%"
      
      # Pod Restarts
      - alert: PodRestartingTooOften
        expr: increase(kube_pod_container_status_restarts_total{namespace="ai-subsidy"}[1h]) > 3
        for: 5m
        labels:
          severity: warning
          service: kubernetes
        annotations:
          summary: "Pod restarting too often"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted {{ $value }} times in the last hour"
      
      # Disk Space
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 5m
        labels:
          severity: critical
          service: infrastructure
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 10% on {{ $labels.instance }}"
      
      # Request Volume
      - alert: LowRequestVolume
        expr: rate(http_requests_total{job="ai-subsidy-backend"}[5m]) < 0.1
        for: 15m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "Low request volume"
          description: "Request rate is unusually low: {{ $value }} requests/second"
      
      # SSL Certificate Expiry
      - alert: SSLCertificateExpiry
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 1h
        labels:
          severity: warning
          service: ssl
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in less than 7 days"
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ai-subsidy-alerts
  namespace: monitoring
  labels:
    app: prometheus
    role: alert-rules
spec:
  groups:
  - name: ai-subsidy.rules
    rules:
    # Application Health
    - alert: ApplicationDown
      expr: up{job="ai-subsidy-backend"} == 0
      for: 5m
      labels:
        severity: critical
        service: backend
      annotations:
        summary: "AI Subsidy application is down"
        description: "The AI Subsidy backend application has been down for more than 5 minutes"
    
    # High Response Time
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="ai-subsidy-backend"}[5m])) > 2
      for: 10m
      labels:
        severity: warning
        service: backend
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is {{ $value }}s"
    
    # High Error Rate
    - alert: HighErrorRate
      expr: rate(http_requests_total{job="ai-subsidy-backend",status=~"5.."}[5m]) / rate(http_requests_total{job="ai-subsidy-backend"}[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
        service: backend
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value | humanizePercentage }}"
    
    # Database Connection Issues
    - alert: DatabaseConnectionFailure
      expr: increase(database_connections_failed_total[5m]) > 5
      for: 2m
      labels:
        severity: critical
        service: database
      annotations:
        summary: "Database connection failures"
        description: "{{ $value }} database connection failures in the last 5 minutes"
    
    # AI Service Issues
    - alert: AIServiceHighLatency
      expr: histogram_quantile(0.95, rate(ai_request_duration_seconds_bucket[5m])) > 10
      for: 5m
      labels:
        severity: warning
        service: ai
      annotations:
        summary: "AI service high latency"
        description: "AI service 95th percentile latency is {{ $value }}s"