apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ai-subsidy
data:
  api-url: "https://api.ai-subsidy.example.com"
  app-name: "AI補助金申請システム"
  environment: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ai-subsidy
data:
  cors-origin: "https://ai-subsidy.example.com"
  log-level: "info"
  session-timeout: "3600"
  max-file-size: "10485760"  # 10MB
  allowed-file-types: "pdf,doc,docx,xls,xlsx,jpg,jpeg,png"