apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-subsidy-uploads
  namespace: ai-subsidy
  labels:
    app: ai-subsidy
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 100Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
  labels:
    app: ai-subsidy
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-xxxxxxxx  # Replace with actual EFS ID
  directoryPerms: "0755"
mountOptions:
  - tls