apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: ai-subsidy
type: Opaque
stringData:
  url: "postgresql://USERNAME:PASSWORD@RDS_ENDPOINT:5432/DATABASE_NAME?sslmode=require"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: ai-subsidy
type: Opaque
stringData:
  url: "rediss://:AUTH_TOKEN@REDIS_ENDPOINT:6379/0"
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-keys-secret
  namespace: ai-subsidy
type: Opaque
stringData:
  openai-key: "YOUR_OPENAI_API_KEY"
  anthropic-key: "YOUR_ANTHROPIC_API_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: ai-subsidy
type: Opaque
stringData:
  jwt-secret: "YOUR_JWT_SECRET_KEY"
  encryption-key: "YOUR_ENCRYPTION_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: ai-subsidy
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: BASE64_ENCODED_DOCKER_CONFIG